services:
  passivbot:
    build: .
    container_name: passivbot
    restart: unless-stopped
    volumes:
      - ./:/usr/src/passivbot/
    working_dir: /usr/src/passivbot
    #command: /bin/sh -c "while sleep 1000; do :; done"
    command: python3 src/backtest.py
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
