services:
    passivbot_optimize:
        container_name: passivbot-optimize
        image: passivbot
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./backtests:/usr/src/passivbot/backtests
            - ./cache:/usr/src/passivbot/cache
            - ./caches:/usr/src/passivbot/caches
            - ./configs:/usr/src/passivbot/configs
            - ./historical_data:/usr/src/passivbot/historical_data
            - ./notebooks:/usr/src/passivbot/notebooks
            - ./optimize_results:/usr/src/passivbot/optimize_results
            - ./optimize_results_analysis:/usr/src/passivbot/optimize_results_analysis
            - ./src:/usr/src/passivbot/src
            - ./api-keys.json:/usr/src/passivbot/api-keys.json:ro
            - ./broker_codes.hjson:/usr/src/passivbot/broker_codes.hjson:ro
        working_dir: /usr/src/passivbot
        command: ["python", "src/optimize.py", "configs/bybit/bybit-0.1.5.json"]
        # command:
        #     [
        #         "python",
        #         "src/tools/extract_best_config.py",
        #         "optimize_results/2025-02-12T17_57_31_combined_406days_9_coins_4a17da98_all_results.txt",
        #         "-v",
        #     ]
